name: matchbox
channels:
  - defaults
dependencies:
  - git-lfs
  - git
  - pandas
  - astropy
  - python==3.8
  - scipy
  - scikit-learn
  - fasteners
  - intervaltree
  - networkx
  - jupyterlab
  - matplotlib
